using System;
using System.Collections.Generic;
using Stellar.Abstractions.Domain;
using Stellar.Abstractions.Services;

namespace Stellar.RaidManager;

// ── Punctuate Mark Presets — share code (export / import) ──────────────────────────────────────────────────────
//
// Players share a preset by copying a short "RMP1.…" code and pasting it on another machine. The wire format and its
// strict validation live in MarkPresetCode.cs (pure, no Unity); this partial maps the plugin's private
// MarkPreset/MarkStep/MarkPos to the codec DTOs, owns the export code state, and talks to the clipboard. The two
// buttons (Import under the create row, Export in the step panel) are built here and slotted into BuildMarksRoot
// (Plugin.Marks.Ui.cs) so that file stays small. Each opens its own popup window anchored to the button: Import →
// paste window (Plugin.Marks.ImportWindow.cs, decoded by ImportFromBuffer); Export → copy window
// (Plugin.Marks.ExportWindow.cs, showing the code generated by ExportActivePreset).
//
// Export is ON DEMAND and the code is a snapshot: anything that changes what it would contain (switching /
// deactivating / deleting / renaming the preset, saving or deleting a step, editing a comment) calls
// ClearExportCode(), which also closes the export window, so it never shows a stale code. HasExportCode additionally
// gates on _exportPresetIdx == _activeIndex as a belt-and-braces check.
//
// Clipboard: UnityEngine.GUIUtility.systemCopyBuffer — the IL2CPP-safe clipboard path already used by CombatMeter's
// CopyUploadLink. Both directions (Copy here, "Paste from clipboard" in the import window) are wrapped in try/catch;
// a clipboard failure only sets a status line.
public sealed partial class Plugin
{
    private string _exportCode = "";
    private int _exportPresetIdx = -1;

    private bool HasExportCode() => _exportCode.Length > 0 && _exportPresetIdx == _activeIndex && _activeIndex >= 0;

    private void ClearExportCode()
    {
        CloseExportWindow();   // stale code → close rather than regenerate (Plugin.Marks.ExportWindow.cs header)
        if (_exportCode.Length == 0) return;
        _exportCode = "";
        _exportPresetIdx = -1;
        _marksWindow?.MarkDirty();
    }

    private void ExportActivePreset()
    {
        var p = ActivePreset();
        if (p == null) return;

        if (!MarkPresetCode.TryEncode(ToCodePreset(p), out string code, out var err))
        {
            ClearExportCode();
            _marksStatus = _loc.T("rm.marks.exportFailed");
            _marksWindow?.MarkDirty();
            _services.Log.Warning($"[MarkPresets] export of '{p.Name}' failed: {err}");
            return;
        }

        _exportCode = code;
        _exportPresetIdx = _activeIndex;
        _marksStatus = _loc.TFormat("rm.marks.exported", p.Name);
        _marksWindow?.MarkDirty();
        _services.Log.Info($"[MarkPresets] exported '{p.Name}' ({p.Steps.Count - 1} steps, {code.Length} chars)");
    }

    private void CopyExportCode()
    {
        if (!HasExportCode()) return;
        try
        {
            UnityEngine.GUIUtility.systemCopyBuffer = _exportCode;   // plugins may reference UnityEngine; IL2CPP-safe clipboard
            _marksStatus = _loc.T("rm.marks.copied");
            SetExportStatus(_loc.T("rm.marks.copied"), ok: true);          // feedback in the export window too
        }
        catch (Exception ex)
        {
            _marksStatus = _loc.T("rm.marks.clipboardFailed");
            SetExportStatus(_loc.T("rm.marks.clipboardFailed"), ok: false);
            _services.Log.Warning($"[MarkPresets] clipboard write failed: {ex.Message}");
        }
        _marksWindow?.MarkDirty();
    }

    // Decodes _importBuffer (typed/pasted into the import window, Plugin.Marks.ImportWindow.cs). Failures stay IN the
    // import window (status there, buffer kept so the user can fix it); success reports in the marks window's status
    // line and closes the import window.
    private void ImportFromBuffer()
    {
        // Invalid code → status only; the preset list is untouched. TryDecode strips all whitespace itself.
        if (!MarkPresetCode.TryDecode(_importBuffer ?? "", out var dto, out var err))
        {
            SetImportStatus(_loc.T("rm.marks.importInvalid"), ok: false);
            _services.Log.Info($"[MarkPresets] import rejected: {err}");
            return;
        }
        if (_presets.Count >= MaxPresets)
        {
            SetImportStatus(_loc.TFormat("rm.marks.limit", MaxPresets), ok: false);
            return;
        }

        // Same case-insensitive uniqueness rule as CreatePreset/CommitRename, but resolved instead of refused:
        // importing your own export (or a friend's same-named preset) yields "Name (2)", "Name (3)", …
        string name = dto.Name.Trim();
        if (NameTaken(name))
        {
            int n = 2;
            while (NameTaken($"{name} ({n})")) n++;
            name = $"{name} ({n})";
        }

        // Re-create the permanent blank Start anchor at Steps[0]; the code carries only the real steps (1..N).
        var preset = new MarkPreset { Name = name, Steps = { new MarkStep() } };
        foreach (var st in dto.Steps)
        {
            var step = new MarkStep { Comment = st.Comment ?? "" };
            foreach (var m in st.Marks) step.Marks.Add(new MarkPos { Slot = m.Slot, X = m.X, Y = m.Y, Z = m.Z });
            preset.Steps.Add(step);
        }

        _presets.Add(preset);   // appended, NOT activated — the user picks it like any other preset
        _editingIdx = -1;       // list changed — drop any in-progress rename (it is keyed by index)
        CancelStepCommentEdit();
        SavePresetsToConfig();
        _marksStatus = _loc.TFormat("rm.marks.imported", name, dto.Steps.Count);
        _marksWindow?.MarkDirty();
        _importBuffer = "";
        SetImportStatus("", ok: true);
        _importWindow?.SetVisible(false);   // done — the result shows in the marks window's status line
        _services.Log.Info($"[MarkPresets] imported '{name}' ({dto.Steps.Count} steps)");
    }

    private bool NameTaken(string name)
        => _presets.Exists(p => string.Equals(p.Name, name, StringComparison.OrdinalIgnoreCase));

    // Steps[0] is the blank Start anchor — never exported; the importer re-creates it.
    private static MarkCodePreset ToCodePreset(MarkPreset p)
    {
        var dto = new MarkCodePreset { Name = p.Name ?? "" };
        for (int i = 1; i < p.Steps.Count; i++)
        {
            var st = p.Steps[i];
            var s = new MarkCodeStep { Comment = st.Comment ?? "" };
            foreach (var m in st.Marks) s.Marks.Add(new MarkCodeMark(m.Slot, m.X, m.Y, m.Z));
            dto.Steps.Add(s);
        }
        return dto;
    }

    // ── UI pieces (slotted into BuildMarksRoot) ──────────────────────────────────────────────────────────────────
    // Full-width button under the create row — opens the paste window (Plugin.Marks.ImportWindow.cs) anchored to this
    // button. OnClick AND OnClickWithRect both fire on a click, so OnClick is a no-op and the open happens once, in
    // the rect callback that knows where the button is.
    private HudElement BuildMarksImportButton()
        => new ButtonElement(() => _loc.T("rm.marks.import"), OnClick: () => { })
           { OnClickWithRect = OpenImportWindowAt };

    // Own row in the step panel: Save Step / Delete Step already fill the 440 window in the longer locales
    // (e.g. fil "Tanggalin ang Hakbang"), so a third button there would squeeze/clip. Generates the code and opens the
    // copy window (Plugin.Marks.ExportWindow.cs) anchored to this button — same no-op OnClick + OnClickWithRect split
    // as the Import button.
    private HudElement BuildMarksExportButton()
        => new ButtonElement(() => _loc.T("rm.marks.export"), OnClick: () => { })
           { OnClickWithRect = OpenExportWindowAt };
}
