using System;
using System.Collections.Generic;

namespace Stellar.RaidManager;

// GENERATED table (keep in sync with Lang/*.json "rm.mech.n.*"): English mechanic / scene / arena name → catalog key.
// The tracker data stays English (it mirrors upstream resonance-logs-cn's en-US strings and keys the hit offsets);
// McText.T maps a known English name to the active language at display/compose time.
internal static partial class McText
{
    private static readonly Dictionary<string, string> Names = new(StringComparer.Ordinal)
    {
        ["Phase"] = "rm.mech.n.phase",
        ["Edge-Mid Explosion"] = "rm.mech.n.edgeMid",
        ["Corner Explosion"] = "rm.mech.n.corner",
        ["Electromagnetic Pulse"] = "rm.mech.n.emp",
        ["Share / Decay"] = "rm.mech.n.shareDecayGroup",
        ["Share / Decay / Spread"] = "rm.mech.n.shareGroup",
        ["Mirage Share / Decay / Spread"] = "rm.mech.n.mirageShareGroup",
        ["Share"] = "rm.mech.n.share",
        ["Mirage Share"] = "rm.mech.n.mirageShare",
        ["Decay"] = "rm.mech.n.decay",
        ["Spread"] = "rm.mech.n.spread",
        ["Mirage Decay"] = "rm.mech.n.mirageDecay",
        ["Mirage Spread"] = "rm.mech.n.mirageSpread",
        ["Divine Scale - Causal Jump"] = "rm.mech.n.causalJumpGroup",
        ["Causal Jump Ricochet"] = "rm.mech.n.causalJump",
        ["Normal Target / Decay Target"] = "rm.mech.n.normalDecayGroup",
        ["Normal Target"] = "rm.mech.n.normalTarget",
        ["Decay Target"] = "rm.mech.n.decayTarget",
        ["Hit Order"] = "rm.mech.n.hitOrder",
        ["Mark 1"] = "rm.mech.n.mark1",
        ["Mark 2"] = "rm.mech.n.mark2",
        ["Mark 3"] = "rm.mech.n.mark3",
        ["Execution Sentence"] = "rm.mech.n.execution",
        ["Execution Sentence - Mirage"] = "rm.mech.n.executionMirage",
        ["Divine Trick - Execution Sentence"] = "rm.mech.n.divineTrick",
        ["Divine Trick - Execution Sentence - Mirage"] = "rm.mech.n.divineTrickMirage",
        ["Pinball"] = "rm.mech.n.pinball",
        ["Pinball Cast"] = "rm.mech.n.pinballCast",
        ["Ball"] = "rm.mech.n.ball",
        ["Electromagnetic Ring Sequence"] = "rm.mech.n.ringSeq",
        ["Inner Ring"] = "rm.mech.n.innerRing",
        ["Middle Ring"] = "rm.mech.n.middleRing",
        ["Outer Ring"] = "rm.mech.n.outerRing",
        ["Phase Mapping — Danger"] = "rm.mech.n.phaseDanger",
        ["Divine Scale - Preset Return"] = "rm.mech.n.presetReturn",
        ["Top Left"] = "rm.mech.n.topLeft",
        ["Top Middle"] = "rm.mech.n.topMid",
        ["Top Right"] = "rm.mech.n.topRight",
        ["Middle Left"] = "rm.mech.n.midLeft",
        ["Center"] = "rm.mech.n.center",
        ["Middle Right"] = "rm.mech.n.midRight",
        ["Bottom Left"] = "rm.mech.n.bottomLeft",
        ["Bottom Middle"] = "rm.mech.n.bottomMid",
        ["Bottom Right"] = "rm.mech.n.bottomRight",
        ["Energy Pillar Target"] = "rm.mech.n.energyPillarTarget",
        ["Energy Pillar"] = "rm.mech.n.energyPillar",
        ["Energy Pillar Short"] = "rm.mech.n.energyPillarShort",
        ["Half-Field Charge Target"] = "rm.mech.n.chargeTarget",
        ["Left Charge"] = "rm.mech.n.leftCharge",
        ["Right Charge"] = "rm.mech.n.rightCharge",
        ["Random Half-Field Charge"] = "rm.mech.n.randomCharge",
        ["Puzzle Target"] = "rm.mech.n.puzzleTarget",
        ["Puzzle Piece 1"] = "rm.mech.n.puzzle1",
        ["Puzzle Piece 2"] = "rm.mech.n.puzzle2",
        ["Blue Tower"] = "rm.mech.n.blueTower",
        ["Blue Tower Activating"] = "rm.mech.n.blueTowerActivating",
        ["Charge Clone"] = "rm.mech.n.chargeClone",
        ["Left-Hand Clone"] = "rm.mech.n.leftClone",
        ["Right-Hand Clone"] = "rm.mech.n.rightClone",
        ["Sticky Bomb"] = "rm.mech.n.stickyBomb",
        ["Sticky Bomb Countdown"] = "rm.mech.n.stickyBombCountdown",
        ["Portal"] = "rm.mech.n.portal",
        ["Correct Portal"] = "rm.mech.n.correctPortal",
        ["Gravity Blast"] = "rm.mech.n.gravityBlast",
        ["Blast Countdown"] = "rm.mech.n.blastCountdown",
        ["Tina · Mechanic"] = "rm.mech.n.tinaMechanic",
        ["Heavy Wound"] = "rm.mech.n.heavyWound",
        ["Red-Light Bind"] = "rm.mech.n.redLightBind",
        ["Pizza Danger Zone"] = "rm.mech.n.pizzaDanger",
        ["Pizza · Slow Wave"] = "rm.mech.n.pizzaSlow",
        ["Pizza · Fast Wave"] = "rm.mech.n.pizzaFast",
        ["Duet Color"] = "rm.mech.n.duetColor",
        ["Duet - Ice"] = "rm.mech.n.duetIce",
        ["Duet - Water"] = "rm.mech.n.duetWater",
        ["Nabo Matrix Callout"] = "rm.mech.n.matrixCallout",
        ["Mechanism Callout"] = "rm.mech.n.mechanismCallout",
        ["Purple Pizza"] = "rm.mech.n.purplePizza",
        ["Orange Pizza"] = "rm.mech.n.orangePizza",
        ["Ice/Sea Wave Safe Zone"] = "rm.mech.n.waveZone",
        ["Ice Wave Safe"] = "rm.mech.n.iceWaveSafe",
        ["Sea Wave Safe"] = "rm.mech.n.seaWaveSafe",
        ["Vertical"] = "rm.mech.n.vertical",
        ["Horizontal"] = "rm.mech.n.horizontal",
        ["Cross Intersection"] = "rm.mech.n.crossSafe",
        ["Single Wave Safe"] = "rm.mech.n.singleWaveSafe",
        ["Wheels"] = "rm.mech.n.wheels",
        ["Fate Wheel · Stack"] = "rm.mech.n.fateWheel",
        ["Woe Wheel · Spread"] = "rm.mech.n.woeWheel",
        ["Despair Wheel"] = "rm.mech.n.despairWheel",
        ["Void-Mark Swap"] = "rm.mech.n.voidMarkSwap",
        ["Void-Mark Resolve"] = "rm.mech.n.voidMarkResolve",
        ["Already matched"] = "rm.mech.n.alreadyMatched",
        ["White"] = "rm.mech.n.white",
        ["Black"] = "rm.mech.n.black",
        ["Swap Orbs"] = "rm.mech.n.swapOrbs",
        ["Swapping"] = "rm.mech.n.swapping",
        ["Shadow of Heluga"] = "rm.mech.n.shadowHeluga",
        ["Energy Orb Tracking"] = "rm.mech.n.energyOrb",
        ["Near/Far Chain"] = "rm.mech.n.nearFarChain",
        ["Near"] = "rm.mech.n.near",
        ["Far"] = "rm.mech.n.far",
    };
}
